// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFrDQy0mKiHOhPqPa7WXxB0D0XN0nlqEg',
    appId: '1:500402254803:web:7dca78d00e2e28e9163526',
    messagingSenderId: '500402254803',
    projectId: 'instant-photos-9a258',
    authDomain: 'instant-photos-9a258.firebaseapp.com',
    storageBucket: 'instant-photos-9a258.firebasestorage.app',
    measurementId: 'G-FR03G814H6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYh0IgSiz57hi8LsyX3bBCnU77S7VfP8E',
    appId: '1:500402254803:ios:1519590dfb84371c163526',
    messagingSenderId: '500402254803',
    projectId: 'instant-photos-9a258',
    storageBucket: 'instant-photos-9a258.firebasestorage.app',
    iosBundleId: 'com.example.majorProjectWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFrDQy0mKiHOhPqPa7WXxB0D0XN0nlqEg',
    appId: '1:500402254803:web:38e049fd4aecc0cf163526',
    messagingSenderId: '500402254803',
    projectId: 'instant-photos-9a258',
    authDomain: 'instant-photos-9a258.firebaseapp.com',
    storageBucket: 'instant-photos-9a258.firebasestorage.app',
    measurementId: 'G-FBQ33WLF99',
  );
}
